### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by axac** [YunoHost-Apps/photonix_ynh#14]
Mon serveur YunoHost
Matériel: Freebox Delta carte ARM 64 (VM Debian 10)
Version de YunoHost: 4.2.6.1
J’ai accès à mon serveur : En SSH | Par la webadmin | En direct avec un clavier/écran |
Êtes-vous dans un contexte particulier ou avez-vous effectué des modifications particulières sur votre instance ? : non

Description of the problem
Hello, thank you already for the job done!
I tried to install it, but the installation stops, the log:
https://paste.yunohost.org/raw/botahimosa

Thanks !

Description du problème
Bonjour, déjà merci pour le travail fait !.
J’ai désinstaller la version 1.6 (la mise à jour n’aboutissait pas).
Et j’ai essayé de l’installer, mais l’installation se stoppe, le journal :
https://paste.yunohost.org/raw/botahimosa

Merci !

**Comment by tituspijean** [comment]
Related to #7, I think.
